version: "3"
services:
  #* Database to use for storing data from keystone
  opensds-mariadb:
    container_name: opensds-mariadb
    image: "mariadb:10.10.2-jammy"
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config:/etc/mysql/conf.d/
    ports:
      - "3006:3006"
    environment:
      MARIADB_ROOT_PASSWORD: "opensds@123"

 #*  keystone service     
  opensds-keystone:
    container_name: opensds-keystone
    depends_on:
       - opensds-mariadb
    image: "joseph/soda-keystone:v1"
    restart: always
    environment:
       HOST_IP: "192.168.1.4"
       KEYSTONE_DB_HOST : "opensds-mariadb"
       OS_AUTH_URL: "http://192.168.1.4:5000/v3"
       OS_USERNAME: admin
       OS_PASSWORD: "opensds#123"
       OS_PROJECT_NAME: admin
       OS_USER_DOMAIN_NAME: Default
       OS_PROJECT_DOMAIN_NAME: Default
       OS_IDENTITY_API_VERSION: 3
       STACK_PASSWORD: "opensds#123"
    ports:
      - "5000:5000"